---
- hosts: all
  become: yes
  tasks:
    - include_tasks: createfileplaybook.yaml

    - name: i want to install apache2 on node server
      apt:
        name: apache2
        state: present
        