---
- hosts: javaserver
  become: yes
  tasks:
    - name: Include external task file
      include_tasks: createfileplaybook.yaml

    - name: Install Apache2 on node server
      apt:
        name: apache2
        state: present

