---
- hosts: all
  become: yes
  tasks:
    - name: Include task file
      include_tasks: createfileplaybook.yaml

    - name: Install Apache2
      apt:
        name: apache2
        state: present


