---
- hosts: all
  become: yes
  tasks:

    - name: Install Java 17 on RHEL
      dnf:
        name: java-17-openjdk
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Java 17 on Ubuntu
      apt:
        name: openjdk-17-jre
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
